version: "3.7"

services:
  kuali:
    container_name: cn_kuali
    image: kooldev/php:8.4-nginx-prod
    restart: always
    volumes:
      - "./:/app/kuali"
      - "./default.tmpl:/kool/default.tmpl"
    ports:
      - "8195:80"
    environment:
      - APP_NAME=kuali
      - PHP_FPM_LISTEN=/run/php-fpm.sock
      - NGINX_LISTEN=80
      - NGINX_ROOT=/app/kuali/public
      - NGINX_INDEX=index.php
      - NGINX_CLIENT_MAX_BODY_SIZE=150M
      - PHP_UPLOAD_MAX_FILESIZE=150M
      - PHP_POST_MAX_SIZE=150M
      - PHP_MEMORY_LIMIT=512M
      - NGINX_PHP_FPM=unix:/run/php-fpm.sock
      - NGINX_FASTCGI_READ_TIMEOUT=60s
      - NGINX_FASTCGI_BUFFERS=8 8k
      - NGINX_FASTCGI_BUFFER_SIZE=16k

  build_kuali:
    container_name: cn_kuali_node
    image: node:20
    working_dir: /app/kuali
    volumes:
      - "./:/app/kuali"
    command: sh -c "npm install && npm run build"

